Repository stolostron/clusterlifecycle-state-metrics, pull requests merged in 2024-12, with the labels that each got.

#194 chore(deps): update konflux references
  .tekton/clusterlifecycle-state-metrics-mce-28-pull-request.yaml
  .tekton/clusterlifecycle-state-metrics-mce-28-push.yaml
Labels: approved, lgtm, dco-signoff: yes

#195 :seedling: Update konflux CEL from backplane-2.8 to main
  .tekton/clusterlifecycle-state-metrics-mce-28-pull-request.yaml
  .tekton/clusterlifecycle-state-metrics-mce-28-push.yaml
Labels: approved, lgtm, dco-signoff: yes

#199 :seedling: Update konflux CEL from backplane-2.8 to main
  .tekton/OWNERS
Labels: approved, lgtm, dco-signoff: yes

#200 :seedling: [main] update konflux files
  .tekton/clusterlifecycle-state-metrics-mce-28-pull-request.yaml
  .tekton/clusterlifecycle-state-metrics-mce-28-push.yaml
Labels: approved, dco-signoff: yes

#206 :seedling: [backplane-2.7] update konflux files
  .tekton/OWNERS
  .tekton/clusterlifecycle-state-metrics-mce-27-pull-request.yaml
  .tekton/clusterlifecycle-state-metrics-mce-27-push.yaml
Labels: dco-signoff: yes

#207 :seedling: [backplane-2.6] update konflux files
  .tekton/OWNERS
  .tekton/clusterlifecycle-state-metrics-mce-26-pull-request.yaml
  .tekton/clusterlifecycle-state-metrics-mce-26-push.yaml
Labels: dco-signoff: yes

#208 :seedling: [backplane-2.5] update konflux files
  .tekton/OWNERS
  .tekton/clusterlifecycle-state-metrics-mce-25-pull-request.yaml
  .tekton/clusterlifecycle-state-metrics-mce-25-push.yaml
Labels: dco-signoff: yes

#209 :seedling: [backplane-2.4] update konflux files
  .tekton/OWNERS
  .tekton/clusterlifecycle-state-metrics-1tww-pull-request.yaml
  .tekton/clusterlifecycle-state-metrics-1tww-push.yaml
Labels: dco-signoff: yes

#210 🐛 Remove hosted cluster label for sd manifestworks timestamp metrics
  pkg/generators/work/manifestworktimestamp.go
  pkg/generators/work/manifestworktimestamp_test.go
Labels: approved, lgtm, dco-signoff: yes
